# Feed Forward Neural Network

In [1]:
from IPython.display import Image
%matplotlib inline

In [3]:
#Image(filename= 'Insert your image file')

# Activating neural network via forward propagation

In [6]:
# insert filename sigmoid function
#Image(filename = 'Sigmoid file')

# Implement a multilayer perceptron - Practise Assignments

In [14]:
import numpy as np
import sys
import random

In [17]:
class NeuralNetworkMLP:
    def __init__(self, input_layer_size, hidden_layer_size, output_layer_size):
        
        random.seed(2)

        # Initialize weights and biases for the hidden and output layers
        self.synaptic_weights_hidden = 2 * np.random.rand(input_layer_size, hidden_layer_size) - 1
        self.bias_hidden = np.zeros((1, hidden_layer_size))

        self.synaptic_weights_output = 2 * np.random.rand(hidden_layer_size, output_layer_size) - 1
        self.bias_output = np.zeros((1, output_layer_size))

    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def think(self, inputs):
        # Forward pass through the hidden layer
        hidden_layer_output = self.__sigmoid(np.dot(inputs, self.synaptic_weights_hidden) + self.bias_hidden)

        # Forward pass through the output layer
        output_layer_output = self.__sigmoid(np.dot(hidden_layer_output, self.synaptic_weights_output) + self.bias_output)

        return output_layer_output

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations, learning_rate):
        for iteration in range(number_of_training_iterations):
            # Forward pass
            hidden_layer_input = np.dot(training_set_inputs, self.synaptic_weights_hidden) + self.bias_hidden
            hidden_layer_output = self.__sigmoid(hidden_layer_input)

            output_layer_input = np.dot(hidden_layer_output, self.synaptic_weights_output) + self.bias_output
            output_layer_output = self.__sigmoid(output_layer_input)

            # Calculate the error
            output_error = training_set_outputs - output_layer_output

            # Backpropagation
            output_delta = output_error * self.__sigmoid_derivative(output_layer_output)
            hidden_layer_error = output_delta.dot(self.synaptic_weights_output.T)
            hidden_layer_delta = hidden_layer_error * self.__sigmoid_derivative(hidden_layer_output)

            # Update weights and biases
            self.synaptic_weights_output += hidden_layer_output.T.dot(output_delta) * learning_rate
            self.bias_output += np.sum(output_delta, axis=0) * learning_rate
            self.synaptic_weights_hidden += training_set_inputs.T.dot(hidden_layer_delta) * learning_rate
            self.bias_hidden += np.sum(hidden_layer_delta, axis=0) * learning_rate


In [19]:
if __name__ == '__main__':
    input_layer_size = 3
    hidden_layer_size = 4
    output_layer_size = 1

    neural_network_mlp = NeuralNetworkMLP(input_layer_size, hidden_layer_size, output_layer_size)
    
    print('Random Starting weights (Hidden Layer):\n')
    print(neural_network_mlp.synaptic_weights_hidden)
    
    print('Random Starting weights (Output Layer):\n')
    print(neural_network_mlp.synaptic_weights_output)
    
    training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = np.array([[0, 1, 1, 0]]).T
    
    learning_rate = 0.1
    num_training_iterations = 10000


Random Starting weights (Hidden Layer):

[[-0.79744261  0.90359041  0.88129852 -0.56021557]
 [-0.29004125 -0.73481718  0.45455351  0.14748982]
 [ 0.71136919  0.20453537  0.6954095   0.79829877]]
Random Starting weights (Output Layer):

[[ 0.54023184]
 [ 0.53811349]
 [-0.91500138]
 [-0.70605316]]


In [21]:
# Train the network
print('*' * 23 + ' Neural Network Training Phase ' + '*' * 23)
neural_network_mlp.train(training_set_inputs, training_set_outputs, num_training_iterations, learning_rate)
print('New Weights after Training (Hidden Layer):\n')
print(neural_network_mlp.synaptic_weights_hidden)
print('New Weights after Training (Output Layer):\n')
print(neural_network_mlp.synaptic_weights_output)
print()

# Test the network
new_input = np.array([1, 0, 0])
print('Considering the new situation [1, 0, 0] --> ?:')
output = neural_network_mlp.think(new_input)
print(output[0])


*********************** Neural Network Training Phase ***********************
New Weights after Training (Hidden Layer):

[[-1.24176650e+00  4.34569817e+00  5.30007552e-01 -4.18182855e+00]
 [-3.29772354e-01 -3.05291163e-01  4.99514010e-01 -4.31398838e-03]
 [ 7.10302936e-01 -8.23490529e-01  8.75412291e-01  1.36734613e+00]]
New Weights after Training (Output Layer):

[[-1.1493899 ]
 [ 5.46607871]
 [ 0.18879108]
 [-5.24033116]]

Considering the new situation [1, 0, 0] --> ?:
[0.99406383]
